// <auto-generated />
namespace ControleGames.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remover_Distribuidora : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remover_Distribuidora));
        
        string IMigrationMetadata.Id
        {
            get { return "201511241757009_Remover_Distribuidora"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
